### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JonhSilver** [berkmancenter/mediacloud-ultimate_sitemap_parser#11]
Installed Usp.tree file differ from https://ultimate-sitemap-parser.readthedocs.io/en/latest/_modules/usp/tree.html#sitemap_tree_for_homepage and do not include _UNPUBLISHED_SITEMAP_PATHS

my site use https://www.site.com/sitemap-index.xml which download sitemap.xml.gz 

which include
<sitemap>
    <loc>https://*.amazonaws.com/*sitemap_00.xml.gz</loc>
    <lastmod>2019-07-16</lastmod>
  </sitemap>
  <sitemap>
    <loc>https://*.amazonaws.com/*sitemap_01.xml.gz</loc>
    <lastmod>2019-07-16</lastmod>
  </sitemap>
  <sitemap>

usp.objects.py does not include IndexWebsiteSitemap

**Comment by pypt** [comment]
How are you installing the module? Have you tried the latest 0.3 version from PyPI?

**Comment by JonhSilver** [comment]
pip install ultimate_sitemap_parser

c:\Python37>pip install ultimate-sitemap-parser
Requirement already satisfied: ultimate-sitemap-parser in c:\python37\lib\site-p
ackages (0.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\python37\lib\si
te-packages (from ultimate-sitemap-parser) (2.8.0)
Requirement already satisfied: attrs>=18.2.0 in c:\python37\lib\site-packages (f
rom ultimate-sitemap-parser) (19.1.0)
Requirement already satisfied: requests>=2.2.1 in c:\python37\lib\site-packages
(from ultimate-sitemap-parser) (2.22.0)
Requirement already satisfied: six>=1.5 in c:\python37\lib\site-packages (from p
ython-dateutil<3.0.0,>=2.1->ultimate-sitemap-parser) (1.12.0)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python37\lib\site-packages (
from requests>=2.2.1->ultimate-sitemap-parser) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\python37\lib\site-packag
es (from requests>=2.2.1->ultimate-sitemap-parser) (2019.3.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\pyt
hon37\lib\site-packages (from requests>=2.2.1->ultimate-sitemap-parser) (1.25.3)

Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python37\lib\site-pac
kages (from requests>=2.2.1->ultimate-sitemap-parser) (3.0.4)

**Comment by JonhSilver** [comment]
3.0 version is ok but not found at all sitemap, but it exists

please look and when remove my link
https://www.senukai.lt/sitemap-index.xml

**Comment by kienli** [comment]
> 3.0 version is ok but not found at all sitemap, but it exists

Are you sure, that /sitemap-index.xml should response with a download of sitemap.xml.gz?
It's very unusual and I don't see the justification in Sitemap Protocol: https://www.sitemaps.org/protocol.html#index

I would expect by calling /sitemap-index.xml to get the real XML file (not gzipped.)

`<?xml version="1.0" encoding="utf-8"?>
<sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://sg-lt-data-export.s3.eu-central-1.amazonaws.com/production/senukai_lt/sitemap/lt_sitemap_00.xml.gz</loc>
    <lastmod>2019-07-17</lastmod>
  </sitemap>
...
`

This way version 3.0 should work.

**Comment by kienli** [comment]
> 2. how to get only list of links extracted?

`
from usp.tree import sitemap_tree_for_homepage

tree = sitemap_tree_for_homepage('https://mediacloud.org/')
for item in tree.all_pages():
    print(item.url)
`

**Comment by JonhSilver** [comment]
> > 3.0 version is ok but not found at all sitemap, but it exists
> 
> Are you sure, that /sitemap-index.xml should response with a download of sitemap.xml.gz?
> It's very unusual and I don't see the justification in Sitemap Protocol: https://www.sitemaps.org/protocol.html#index
> 
> I would expect by calling /sitemap-index.xml to get the real XML file (not gzipped.)

> 
> This way version 3.0 should work.

it work if i add to tree.py 'sitemap-index.xml.gz',

please remove links, many thanks

**Comment by kienli** [comment]
I know, why it doesn't work. Because /sitemap-index.xml is not listed in _UNPUBLISHED_SITEMAP_PATHS: https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/blob/afdb8884f9f8182d11026c8e8999cbcaa27885b1/usp/tree.py#L13

There are two ways to solve the issue: 

1. Add your sitemap to robots.txt
2. Ask @pypt to include sitemap-index.xml to _UNPUBLISHED_SITEMAP_PATHS
(Sorry @pypt that I opened the Pandora's box)

**Comment by pypt** [comment]
Thank you for your replies @kienli!

I've added `sitemap-index.xml`, `sitemap_index.xml.gz` and `sitemap-index.xml.gz` to a newly released 0.4.

Logging is a bit verbose but I myself like to see what the code is doing so I'll leave it as-is for now.

I've clarified what returns what in the README: https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser#usage

Closing for now then.
