### ISSUE TITLE
Error in request causes total crash

### ISSUE THREAD

**Issue by bartmachielsen** [berkmancenter/mediacloud-ultimate_sitemap_parser#14]
Because of a time out error on a single sitemap (that does not exist) the entire script crashes. So no other sitemaps are tried and an error is raised:

`   ERROR  [2019-07-26 07:36:22,600 sitemap_scanner:  24]          HTTPSConnectionPool(host='dutchitchannel.nl', port=443): Read timed out. (read timeout=60)
`

**Comment by pypt** [comment]
Thanks, will take a look (unless you'd like to submit a PR!)

**Comment by pypt** [comment]
Fixed, 0.5 released. If you're using a custom web client, have a look at the abstract class changes. If not, should work out of the box.

**Comment by bartmachielsen** [comment]
Thank you!
