### ISSUE TITLE
Optional typing should be set to None for considering as Optional Argument

### ISSUE THREAD

**Issue by jayanthchandra** [berkmancenter/mediacloud-ultimate_sitemap_parser#15]
I noticed that for `RequestsWebClientResponse` constructor the Optional Argument is not set as None which would cause an issue in later stages when making new development/fixes around that. 

https://github.com/berkmancenter/mediacloud-ultimate_sitemap_parser/blob/3c2b076f52ca57412791a21a6cac4210b3468b86/usp/web_client/requests_client.py#L22

This is not an issue, just a suggestion for keeping it clean :)

**Comment by pypt** [comment]
Thanks, fixed!
